local game_data = require("game_data")
local BLOCK_TYPE = game_data.BLOCK_TYPE

return {
    ["gAttack1"] = {
        kommand = "1",
        block_type = BLOCK_TYPE.HIGH,
        startup = 7,
        active = 3,
        recovery = 20,
        cancel = 16,
    },
    ["gAttack1_1"] = {
        kommand = "1,1",
        block_type = BLOCK_TYPE.MID,
        startup = 14,
        active = 3,
        recovery = 20,
        cancel = 24,
    },
    ["gAttack1_1_2"] = {
        kommand = "1,1,2",
        block_type = BLOCK_TYPE.MID,
        startup = 16,
        active = 4,
        recovery = 33,
        cancel = 0,
    },
    ["gAttack1Down"] = {
        kommand = "D+1",
        block_type = BLOCK_TYPE.MID,
        startup = 7,
        active = 3,
        recovery = 23,
        cancel = 15,
    },
    ["gAttack2"] = {
        kommand = "2",
        block_type = BLOCK_TYPE.HIGH,
        startup = 16,
        active = 3,
        recovery = 26,
        cancel = 28,
    },
    ["gAttack2Cancel"] = {
        kommand = "2",
        block_type = BLOCK_TYPE.NONE,
        startup = 1,
        active = 0,
        recovery = 22,
        cancel = 0,
    },
    ["gAttack2Bwd"] = {
        kommand = "2",
        block_type = BLOCK_TYPE.MID,
        startup = 14,
        active = 3,
        recovery = 36,
        cancel = 28,
    },
    ["gAttack2Away"] = {
        kommand = "B+2",
        block_type = BLOCK_TYPE.OVERHEAD,
        startup = 24,
        active = 4,
        recovery = 24,
        cancel = 36,
    },
    ["gAttack2Away_2"] = {
        kommand = "B+2,2",
        block_type = BLOCK_TYPE.OVERHEAD,
        startup = 9,
        active = 3,
        recovery = 37,
        cancel = 0,
    },
    ["gAttack2Towards"] = {
        kommand = "F+2",
        block_type = BLOCK_TYPE.MID,
        startup = 15,
        active = 2,
        recovery = 25,
        cancel = 24,
    },
    ["gAttack2Towards_1"] = {
        kommand = "F+2,1",
        block_type = BLOCK_TYPE.HIGH,
        startup = 17,
        active = 3,
        recovery = 26,
        cancel = 27,
    },
    ["gAttack2Towards_1_2"] = {
        kommand = "F+2,1,2",
        block_type = BLOCK_TYPE.MID,
        startup = 10,
        active = 7,
        recovery = 42,
        cancel = 25,
    },
    ["gAttack2Down"] = {
        kommand = "D+2",
        block_type = BLOCK_TYPE.HIGH,
        startup = 9,
        active = 3,
        recovery = 41,
        cancel = 0,
    },
    ["gAttack3"] = {
        kommand = "3",
        block_type = BLOCK_TYPE.HIGH,
        startup = 18,
        active = 11,
        recovery = 35,
        cancel = 41,
    },
    ["gAttack3Away"] = {
        kommand = "B+3",
        block_type = BLOCK_TYPE.LOW,
        startup = 14,
        active = 4,
        recovery = 26,
        cancel = 26,
    },
    ["gAttack3Away_4"] = {
        kommand = "B+3,4",
        block_type = BLOCK_TYPE.LOW,
        startup = 2,
        active = 30,
        recovery = 24,
        cancel = 11,
    },
    ["gAttack3Towards"] = {
        kommand = "F+3",
        block_type = BLOCK_TYPE.LOW,
        startup = 23,
        active = 9,
        recovery = 25,
        cancel = 14,
    },
    ["gAttack3TowardsCancel"] = {
        kommand = "F+3",
        block_type = BLOCK_TYPE.NONE,
        startup = 1,
        active = 0,
        recovery = 13,
        cancel = 0,
    },
    ["gAttack3Towards_4"] = {
        kommand = "F+3,4",
        block_type = BLOCK_TYPE.HIGH,
        startup = 18,
        active = 15,
        recovery = 26,
        cancel = 0,
    },
    ["gAttack3Down"] = {
        kommand = "D+3",
        block_type = BLOCK_TYPE.LOW,
        startup = 9,
        active = 3,
        recovery = 24,
        cancel = 24,
    },
    ["gAttack4"] = {
        kommand = "4",
        block_type = BLOCK_TYPE.HIGH,
        startup = 11,
        active = 3,
        recovery = 20,
        cancel = 22,
    },
    ["gAttack4_2"] = {
        kommand = "4,2",
        block_type = BLOCK_TYPE.MID,
        startup = 23,
        active = 3,
        recovery = 29,
        cancel = 33,
    },
    ["gAttack4_2_1n3"] = {
        kommand = "4,2,1+3",
        block_type = BLOCK_TYPE.MID,
        startup = 24,
        active = 3,
        recovery = 35,
        cancel = 37,
    },
    ["gAttack4Away"] = {
        kommand = "B+4",
        block_type = BLOCK_TYPE.LOW,
        startup = 14,
        active = 3,
        recovery = 29,
        cancel = 0,
    },
    ["gAttack4Towards"] = {
        kommand = "F+4",
        block_type = BLOCK_TYPE.MID,
        startup = 11,
        active = 4,
        recovery = 34,
        cancel = 23,
    },
    ["gAttack4Towards_3"] = {
        kommand = "F+4,3",
        block_type = BLOCK_TYPE.HIGH,
        startup = 21,
        active = 3,
        recovery = 34,
        cancel = 30,
    },
    ["gAttack4Down"] = {
        kommand = "D+4",
        block_type = BLOCK_TYPE.LOW,
        startup = 13,
        active = 3,
        recovery = 29,
        cancel = 31,
    },

    ["gAttack1JumpUp"] = {
        kommand = "U+F+1",
        block_type = BLOCK_TYPE.MID,
        startup = 7,
        active = 4,
        recovery = 0,
        cancel = 12,
    },
    ["gAttack1JumpForward"] = {
        kommand = "U+F+1",
        block_type = BLOCK_TYPE.MID,
        startup = 7,
        active = 4,
        recovery = 0,
        cancel = 12,
    },
    ["gAttack1JumpBackward"] = {
        kommand = "U+F+1",
        block_type = BLOCK_TYPE.MID,
        startup = 7,
        active = 4,
        recovery = 0,
        cancel = 12,
    },
    ["gAttack1JumpUp_3"] = {
        kommand = "U+F+1,3",
        block_type = BLOCK_TYPE.OVERHEAD,
        startup = 11,
        active = 3,
        recovery = 0,
        cancel = 43,
    },
    ["gAttack1JumpForward_3"] = {
        kommand = "U+F+1,3",
        block_type = BLOCK_TYPE.OVERHEAD,
        startup = 11,
        active = 3,
        recovery = 0,
        cancel = 43,
    },
    ["gAttack1JumpBackward_3"] = {
        kommand = "U+F+1,3",
        block_type = BLOCK_TYPE.OVERHEAD,
        startup = 11,
        active = 3,
        recovery = 0,
        cancel = 43,
    },
    ["gAttack1JumpUp_3_4"] = {
        kommand = "U+F+1,3,4",
        block_type = BLOCK_TYPE.OVERHEAD,
        startup = 14,
        active = 5,
        recovery = 0,
        cancel = 47,
    },
    ["gAttack1JumpForward_3_4"] = {
        kommand = "U+F+1,3,4",
        block_type = BLOCK_TYPE.OVERHEAD,
        startup = 14,
        active = 5,
        recovery = 0,
        cancel = 47,
    },
    ["gAttack1JumpBackward_3_4"] = {
        kommand = "U+F+1,3,4",
        block_type = BLOCK_TYPE.OVERHEAD,
        startup = 14,
        active = 5,
        recovery = 0,
        cancel = 47,
    },
    ["gAttack2JumpUp"] = {
        kommand = "U+F+2",
        block_type = BLOCK_TYPE.MID,
        startup = 9,
        active = 5,
        recovery = 0,
        cancel = 15,
    },
    ["gAttack2JumpForward"] = {
        kommand = "U+F+2",
        block_type = BLOCK_TYPE.MID,
        startup = 9,
        active = 5,
        recovery = 0,
        cancel = 15,
    },
    ["gAttack2JumpBackward"] = {
        kommand = "U+F+2",
        block_type = BLOCK_TYPE.MID,
        startup = 9,
        active = 5,
        recovery = 0,
        cancel = 15,
    },
    ["gAttack2JumpUp_1"] = {
        kommand = "U+F+2,1",
        block_type = BLOCK_TYPE.MID,
        startup = 14,
        active = 4,
        recovery = 0,
        cancel = 43,
    },
    ["gAttack2JumpForward_1"] = {
        kommand = "U+F+2,1",
        block_type = BLOCK_TYPE.MID,
        startup = 14,
        active = 4,
        recovery = 0,
        cancel = 43,
    },
    ["gAttack2JumpBackward_1"] = {
        kommand = "U+F+2,1",
        block_type = BLOCK_TYPE.MID,
        startup = 14,
        active = 4,
        recovery = 0,
        cancel = 43,
    },
    ["gAttack2JumpUp_1_2"] = {
        kommand = "U+F+2,1,2",
        block_type = BLOCK_TYPE.MID,
        startup = 15,
        active = 4,
        recovery = 0,
        cancel = 45,
    },
    ["gAttack2JumpForward_1_2"] = {
        kommand = "U+F+2,1,2",
        block_type = BLOCK_TYPE.MID,
        startup = 15,
        active = 4,
        recovery = 0,
        cancel = 45,
    },
    ["gAttack2JumpBackward_1_2"] = {
        kommand = "U+F+2,1,2",
        block_type = BLOCK_TYPE.MID,
        startup = 15,
        active = 4,
        recovery = 0,
        cancel = 45,
    },
    ["gAttack3JumpUp"] = {
        kommand = "U+F+3",
        block_type = BLOCK_TYPE.MID,
        startup = 9,
        active = 7,
        recovery = 0,
        cancel = 24,
    },
    ["gAttack3JumpForward"] = {
        kommand = "U+F+3",
        block_type = BLOCK_TYPE.MID,
        startup = 9,
        active = 7,
        recovery = 0,
        cancel = 24,
    },
    ["gAttack3JumpBackward"] = {
        kommand = "U+F+3",
        block_type = BLOCK_TYPE.MID,
        startup = 9,
        active = 7,
        recovery = 0,
        cancel = 24,
    },
    ["gAttack4JumpUp"] = {
        kommand = "U+F+4",
        block_type = BLOCK_TYPE.MID,
        startup = 9,
        active = 7,
        recovery = 0,
        cancel = 24,
    },
    ["gAttack4JumpForward"] = {
        kommand = "U+F+4",
        block_type = BLOCK_TYPE.MID,
        startup = 9,
        active = 7,
        recovery = 0,
        cancel = 24,
    },
    ["gAttack4JumpBackward"] = {
        kommand = "U+F+4",
        block_type = BLOCK_TYPE.MID,
        startup = 9,
        active = 7,
        recovery = 0,
        cancel = 24,
    },
}